<div class="layui-tab-item">
    <!-- 表单开始 -->
    <form class="layui-form" id="smsForm" lay-filter="smsForm">
        <input type="hidden" name="typename" value="sms">
        <div class="layui-form-item">
            <label class="layui-form-label">短信配置</label>
            <div class="layui-input-block">
                <input type="radio" name="sms" lay-filter="raSms" value="0" title="关闭" {present name="smstype.value"}{eq name="smstype.value" value="1"}checked{/eq}{/present}/>
                <input type="radio" name="sms" lay-filter="raSms" value="Ali" title="阿里云" {present name="smstype.value"}{eq name="smstype.value" value="Ali"}checked{/eq}{/present}/>
                <input type="radio" name="sms" lay-filter="raSms" value="Tencent" title="腾讯云" {present name="smstype.value"}{eq name="smstype.value" value="Tencent"}checked{/eq}{/present}/>
            </div>
        </div>
        <div id="AliTpl">
            <div class="layui-form-item">
                <label class="layui-form-label">AccessKey</label>
                <div class="layui-input-block">
                    <input name="accesskey" placeholder="请输入AccessKey" value="{$sms.accesskey|default=''}" class="layui-input" autocomplete="off"/>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">SecretKey</label>
                <div class="layui-input-block">
                    <input type="password" name="secretkey" placeholder="请输入SecretKey" value="{$sms.secretkey|default=''}" class="layui-input" autocomplete="off"/>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">短信签名</label>
                <div class="layui-input-block">
                    <input name="bucket" placeholder="请输入短信签名" value="{$sms.bucket|default=''}" class="layui-input" autocomplete="off"/>
                </div>
            </div>
        </div>
        <div id="TencentTpl">
            <div class="layui-form-item">
                <label class="layui-form-label">AccessKey</label>
                <div class="layui-input-block">
                    <input name="accesskey" placeholder="请输入AccessKey" value="{$sms.accesskey|default=''}" class="layui-input" autocomplete="off"/>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">SecretKey</label>
                <div class="layui-input-block">
                    <input type="password" name="secretkey" placeholder="请输入SecretKey" value="{$sms.secretkey|default=''}" class="layui-input" autocomplete="off"/>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">短信签名</label>
                <div class="layui-input-block">
                    <input name="bucket" placeholder="请输入短信签名" value="{$sms.bucket|default=''}" class="layui-input" autocomplete="off"/>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">APP_ID</label>
                <div class="layui-input-block">
                    <input name="domain" placeholder="请输入APP_ID" value="{$sms.domain|default=''}" class="layui-input" autocomplete="off"/>
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-filter="smsSubmit" lay-submit>&emsp;保存配置&emsp;</button>
            </div>
        </div>
    </form>
    <!-- //表单结束 -->
</div>
