{extend name="base" /}

{block name="title"}系统首页{/block}
{block name="body"}

<div class="layui-fluid mx-console-wrapper">
    <div class="layui-row layui-col-space15">
        <!-- 统计图表 -->
        <div class="layui-col-md4 layui-col-sm6">
            <div class="layui-card" style="overflow: hidden;">
                <div class="layui-card-header">按职称统计</div>
                <div class="layui-card-body">
                    <div id="consoleChartsWeek" style="height: 300px;"></div>
                </div>
            </div>
        </div>
        <div class="layui-col-md4 layui-col-sm6">
            <div class="layui-card" style="overflow: hidden;">
                <div class="layui-card-header">按学历统计</div>
                <div class="layui-card-body">
                    <div id="consoleChartsWeek" style="height: 300px;"></div>
                </div>
            </div>
        </div>
        <div class="layui-col-md4 layui-col-sm6">
            <div class="layui-card" style="overflow: hidden;">
                <div class="layui-card-header">按年龄统计</div>
                <div class="layui-card-body">
                    <div id="consoleChartsWeek" style="height: 300px;"></div>
                </div>
            </div>
        </div>
        <div class="layui-col-md4 layui-col-sm6">
            <div class="layui-card" style="overflow: hidden;">
                <div class="layui-card-header">按性别统计</div>
                <div class="layui-card-body">
                    <div id="consoleChartsSex" style="height: 300px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{/block}
{block name="script"}
<script>
    layui.use(['layer'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;

        /** 渲染周统计图表 */
        var myCharts2 = echarts.init(document.getElementById('consoleChartsWeek'));
        var options2 = {
            tooltip: {trigger: 'item', formatter: '{a} <br/>{b}: {c} ({d}%)'},
            color: ['#10B4E8', '#FFA800'],
            legend: {
                orient: 'vertical', right: '0px', top: '0px',
                data: ['已签到', '未签到'], textStyle: {color: '#595959'}
            },
            series: [
                {
                    name: '签到情况',
                    type: 'pie',
                    radius: '50%',
                    data: [
                        {value: 5, name: '已签到'},
                        {value: 10, name: '未签到'}
                    ],
                    label: {
                        normal: {
                            show: true,
                            formatter: '{b}: {c} ({d}%)'
                        }
                    }
                }
            ]
        };
        myCharts2.setOption(options2);
        // 赋值
        myCharts2.setOption({series: [{data: [5, 9, 6, 3, 10]}, {data: [10, 6, 9, 12, 5]}]});

    });
</script>
{/block}