{extend name="base" /}
{block name="body"}
<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://printjs-4de6.kxcdn.com/print.min.css">
<form id="mxForm" lay-filter="mxForm" class="layui-form" style="background:#f5f7f9;">
    <div class="form-group-bottom text-center" id="hidden">
        <p class="layui-btn" id="export-btn">导出</p>
        <button class="layui-btn layui-btn-primary" type="button" id="printer">打印</button>
    </div>
    <div class="layui-container" id="main-body">
        <div class="layui-row">
            <div style="margin: 5px 0; padding: 16px; line-height: 21px; text-align: center; cursor: pointer; box-sizing: border-box; font-weight: 700; background-color: #f7f7f7;" id="title">阳江市妇幼保健院 王莉—护士长 的个人档案</div>
            <div class="layui-col-md12">
                <table class="layui-table">
                    <colgroup>
                        <col width="150">
                        <col width="200">
                        <col width="150">
                        <col width="200">
                    </colgroup>
                    <tbody>
                    <tr>
                        <td>医院名称</td>
                        <td id="departmentname"></td>
                        <td>姓名</td>
                        <td id="nickname"></td>
                        <td>手机号码</td>
                        <td id="phone"></td>
                        <td rowspan="6" colspan="8"  style="text-align: center;"><img style="width: 50%; height: 50%;" id="headimg" src="" alt="Image Description"></td>
                    </tr>
                    <tr>
                        <td>工作科室</td>
                        <td id="department"></td>
                        <td>职务</td>
                        <td id="position_name"></td>
                        <td>性别</td>
                        <td id="sex">女</td>
                    </tr>
                    <tr>
                        <td>证件类型</td>
                        <td id="id_type"></td>
                        <td>证件号码</td>
                        <td id="idcard"></td>
                        <td>出生日期</td>
                        <td id="birthday"></td>
                    </tr>
                    <tr>
                        <td>婚姻状况</td>
                        <td id="marital_status"></td>
                        <td>民族</td>
                        <td id="ethnicity"></td>
                        <td>政治面貌</td>
                        <td id="political_status"></td>
                    </tr>
                    <tr>
                        <td>最高学历</td>
                        <td id="highest_education"></td>
                        <td>最高学历学校</td>
                        <td id="highest_graduate_school"></td>
                        <td>毕业日期</td>
                        <td id="highest_graduate_time"></td>
                    </tr>
                    <tr>
                        <td>初始学历</td>
                        <td id="first_education"></td>
                        <td>初始学历学校</td>
                        <td id="first_graduate_school"></td>
                        <td>毕业日期</td>
                        <td id="first_graduate_time"></td>
                    </tr>
                    <tr>
                        <td>籍贯</td>
                        <td id="native_place"></td>
                        <td>户口所在地</td>
                        <td id="household"></td>
                        <td>住址</td>
                        <td id="address"></td>
                        <td>邮编</td>
                        <td id="zip_code"></td>
                    </tr>
                    <tr>
                        <td>工作电话</td>
                        <td id="work_phone"></td>
                        <td>电子邮箱</td>
                        <td id="email"></td>
                        <td>专科护士</td>
                        <td id="specialized_name"></td>
                        <td>学分卡号</td>
                        <td id="credit_card_number"></td>
                    </tr>
                    <tr>
                        <td>职称</td>
                        <td id="professional_name"></td>
                        <td>层级</td>
                        <td id="level"></td>
                        <td>参加工作日期</td>
                        <td id="work_start_date"></td>
                        <td>人员状态</td>
                        <td id="employment_status">在职</td>
                    </tr>
                    </tbody>
                </table>
                <blockquote class="layui-elem-quote" style="margin-top: 30px;">
                    职务变更记录
                </blockquote>
                <table class="layui-table">
                    <tbody>
                        <tr>
                            <td>序号</td>
                            <td>开始日期</td>
                            <td>结束日期</td>
                            <td>工作科室</td>
                            <td>职务名称</td>
                        </tr>
                        {volist name="department" id="vo"}
                        <tr>
                            <td>{$vo.id}</td>
                            <td>{$vo.start_time}</td>
                            <td>{$vo.end_time}</td>
                            <td>{$vo.department}</td>
                            <td>{$vo.position_name}</td>
                        </tr>
                        {/volist}
                    </tbody>
                </table>
                <blockquote class="layui-elem-quote" style="margin-top: 30px;">
                    缴费记录
                </blockquote>
                <table class="layui-table">
                    <tbody>
                    <tr>
                        <td>序号</td>
                        <td>缴费年份</td>
                        <td>姓名</td>
                        <td>缴费日期</td>
                        <td>缴费金额</td>
                        <td>缴费方式</td>
                    </tr>
                    {volist name="fees" id="vo"}
                    <tr>
                        <td>{$vo.id}</td>
                        <td>{$vo.fees_year}</td>
                        <td>{$vo.nickname}</td>
                        <td>{$vo.fees_time}</td>
                        <td>{$vo.money}</td>
                        <td>{$vo.way}</td>
                    </tr>
                    {/volist}
                    </tbody>
                </table>
                <blockquote class="layui-elem-quote" style="margin-top: 30px;">
                    学习班报名记录
                </blockquote>
                <table class="layui-table">
                    <tbody>
                    <tr>
                        <td>序号</td>
                        <td>学习班分类</td>
                        <td>学习班名称</td>
                        <td>学习地点</td>
                        <td>报名时间</td>
                    </tr>
                    {volist name="trainingSign" id="vo"}
                    <tr>
                        <td>{$vo.id}</td>
                        <td>{$vo.training.classname}</td>
                        <td>{$vo.training.title}</td>
                        <td>{$vo.training.address}</td>
                        <td>{$vo.check_time}</td>
                    </tr>
                    {/volist}
                    </tbody>
                </table>
                <blockquote class="layui-elem-quote" style="margin-top: 30px;">
                    学习班学习记录
                </blockquote>
                <table class="layui-table">
                    <tbody>
                    <tr>
                        <td>序号</td>
                        <td>学习班分类</td>
                        <td>学习班名称</td>
                        <td>学习地点</td>
                        <td>学习时间</td>
                    </tr>
                    {volist name="studySign" id="vo"}
                    <tr>
                        <td>{$vo.id}</td>
                        <td>{$vo.training.classname}</td>
                        <td>{$vo.training.title}</td>
                        <td>{$vo.training.address}</td>
                        <td>{$vo.study_time}</td>
                    </tr>
                    {/volist}
                    </tbody>
                </table>
                <blockquote class="layui-elem-quote" style="margin-top: 30px;">
                    学习班考核记录
                </blockquote>
                <table class="layui-table">
                    <tbody>
                    <tr>
                        <td>序号</td>
                        <td>学习班分类</td>
                        <td>学习班名称</td>
                        <td>学习地点</td>
                        <td>考核时间</td>
                        <td>考核分数</td>
                        <td>考核结果</td>
                    </tr>
                    {volist name="assessSign" id="vo"}
                    <tr>
                        <td>{$vo.id}</td>
                        <td>{$vo.training.classname}</td>
                        <td>{$vo.training.title}</td>
                        <td>{$vo.training.address}</td>
                        <td>{$vo.study_time}</td>
                        <td>{$vo.total_score}</td>
                        <td>{$vo.outcome}</td>
                    </tr>
                    {/volist}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="form-group-bottom text-center">
            <button class="layui-btn layui-btn-primary" type="button" mx-event="closeDialog">取消</button>
        </div>
    </div>
</form>

{/block}

{block name="script"}
<script>
    document.getElementById('export-btn').addEventListener('click', function () {
        var x = document.getElementById("mxForm");
        x.style.display = "none";
        //printJS('main-body', 'html');
        printJS({
            printable: 'main-body',
            type: 'html',
            scanStyles: true,
            header: '<a href="https://blog.quanqinle.com/">check this page online</a>',
            css: ['/static/assets/libs/layui/css/layui.css', '/static/assets/module/admin.css'],
            //style: '.skill-tags {background-color: #eee; padding: 1px 5px; margin: 0 5px 5px 0; display: inline-block;}',
            maxWidth: 2480,
            targetStyles: ['*']
        });
        x.style.display = "inline";
    });
</script>
<script>
    layui.use(['layer', 'form', 'admin', 'xmSelect', 'upload','printer'], function () {
        var $ = layui.jquery;
        var layer = layui.layer;
        var form = layui.form;
        var admin = layui.admin;
        var xmSelect = layui.xmSelect;
        var printer = layui.printer;
        var upload = layui.upload;
        var mData = admin.getLayerData().formdata;
        console.log(mData);
        // 回显数据
        // 更新表格内容
        // 转换sex
        if (mData.sex === 1) {
            document.getElementById('sex').innerText = '男';
        } else if (mData.sex === 0) {
            document.getElementById('sex').innerText = '女';
        }else{
            document.getElementById('sex').innerText = '未知';
        }
        document.getElementById('headimg').src = mData.headimg;
        document.getElementById('departmentname').innerText = mData.departmentname;
        document.getElementById('department').innerText = mData.department;
        document.getElementById('nickname').innerText = mData.nickname;
        document.getElementById('phone').innerText = mData.phone;
        document.getElementById('position_name').innerText = mData.position_name;
        //document.getElementById('sex').innerText = mData.sex;
        document.getElementById('employment_status').innerText = mData.employment_status;
        document.getElementById('credit_card_number').innerText = mData.credit_card_number;
        document.getElementById('work_phone').innerText = mData.work_phone;
        document.getElementById('email').innerText = mData.email;
        document.getElementById('native_place').innerText = mData.native_place;
        document.getElementById('marital_status').innerText = mData.marital_status;
        document.getElementById('ethnicity').innerText = mData.ethnicity;
        document.getElementById('political_status').innerText = mData.political_status;
        document.getElementById('specialized_name').innerText = mData.specialized_name;
        //document.getElementById('specialized_nurse').innerText = mData.specialized_nurse;
        document.getElementById('work_start_date').innerText = mData.work_start_date;
        document.getElementById('id_type').innerText = mData.id_type;
        document.getElementById('idcard').innerText = mData.idcard;
        document.getElementById('birthday').innerText = mData.birthday;
        document.getElementById('level').innerText = mData.level;
        document.getElementById('first_education').innerText = mData.first_education;
        document.getElementById('first_graduate_school').innerText = mData.first_graduate_school;
        document.getElementById('first_graduate_time').innerText = mData.first_graduate_time;
        document.getElementById('highest_education').innerText = mData.highest_education;
        document.getElementById('highest_graduate_school').innerText = mData.highest_graduate_school;
        document.getElementById('highest_graduate_time').innerText = mData.highest_graduate_time;
        document.getElementById('professional_name').innerText = mData.professional_name;
        document.getElementById('zip_code').innerText = mData.zip_code;
        document.getElementById('address').innerText = mData.address;
        document.getElementById('household').innerText = mData.household;
        document.getElementById('title').innerText = mData.departmentname+' '+mData.nickname+'—'+mData.position_name+' 的个人档案';

        // 自定义打印
        $('#printer').on('click', function (e) {
            printer.print({
                hide: ['.layui-btn', '#hidden'],  // 打印时隐藏的元素
                html: $('#mxForm').html(),
                horizontal: false,         // 是否横向打印
                blank: false,              // 是否打开新页面打印
                close: true,              // 如果是打开新页面，打印完是否关闭
                iePreview: false          // 是否兼容ie打印预览
            });
        })

        /*$('#export-btn').on('click', function (e) {
            layer.alert('暂未开放', {icon: 5});
        })*/

    });
</script>
{/block}
